exclude: [nbproject, Gemfile, Gemfile.lock]
baseurl: 
relative_permalinks: false
permalink: /:title
paginate: 10
paginate_path: /page/:num
name: Vivendoporai.com.br
#liveurl: http://localhost:4000
liveurl: http://fititnt.github.io/vivendoporai.com.br